name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: '16'
      - uses: actions/checkout@v2
      - uses: yoshi389111/github-profile-3d-contrib@0.6.0
        with:
          node-version: '16'
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git config user.name YEJIRYOO
          git config user.email emilyryoo5307@gmail.com
          git add -A .
          git commit -m "generated"
          git push
